<script>
    (function() {
        const properties = <?php echo json_encode($block->getProperties())?>;
        const dedupValue = btoa(JSON.stringify({
            id: properties.id,
            items: properties.items.map(item => ({
                id: item.product_id,
                quantity: item.quantity
            }))
        }));
        const dedupKey = `__cvg_started_checkout`;
        if (localStorage.getItem(dedupKey) !== dedupValue) {
            window.cvg({
                method: 'track',
                eventName: 'Started Checkout',
                properties
            })
            localStorage.setItem(dedupKey, dedupValue);
        }
    })();
</script>
