<?php
$properties = json_encode($block->getProperties());
$scriptString = <<<script
    window.cvg||(cvg=function(){cvg.process?cvg.process.apply(cvg,arguments):cvg.queue.push(arguments)},cvg.queue=[]);
    (function() {
        const properties = $properties;
        const dedupValue = btoa(JSON.stringify({
            id: properties.id,
            items: properties.items.map(item => ({
                id: item.product_id,
                quantity: item.quantity
            }))
        }));
        const dedupKey = `__cvg_started_checkout`;
        if (localStorage.getItem(dedupKey) !== dedupValue) {
            window.cvg({
                method: 'track',
                eventName: 'Started Checkout',
                properties
            })
            localStorage.setItem(dedupKey, dedupValue);
        }
    })();
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
