<script>
    (function() {
        const properties = <?php echo json_encode($block->getProperties())?>;
        const profileProperties = <?php echo json_encode($block->getProfileProperties())?>;
        const dedupKey = `__cvg_placed_order`;
        const dedupValue = properties.id;
        if (localStorage.getItem(dedupKey) !== dedupValue) {
            window.cvg({
                method: 'track',
                eventName: 'Placed Order',
                eventID: properties.id,
                properties,
                profileProperties
            })
            localStorage.setItem(dedupKey, dedupValue);
        }
    })();
</script>
